export enum ActionTypes {
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
  SET_TOTAL_PAGES = "SET_TOTAL_PAGES",
  SET_PAGE_SIZE = "SET_PAGE_SIZE",
  SET_FILTER = "SET_FILTER",
  SET_SORTBY = "SET_SORTBY",
  SET_SORTDIRECTION = "SET_SORTDIRECTION",
}
